const CHANGE_BANNERS='CHANGE_BANNERS';
const CHANGE_HOT_RECOMMEND='CHANGE_HOT_RECOMMEND'
const CHANGE_NEW_ALBUM='CHANGE_NEW_ALBUM'
const CHANGE_TOP_RANKING='CHANGE_TOP_RANKING'
const CHANGE_SETTLE_SINGER='CHANGE_SETTLE_SINGER'
const CHANGE_HOT_STREAMER='CHANGE_HOT_STREAMER'
export {CHANGE_BANNERS,CHANGE_HOT_RECOMMEND,CHANGE_NEW_ALBUM,CHANGE_TOP_RANKING,CHANGE_SETTLE_SINGER,
CHANGE_HOT_STREAMER}